# -*- coding: utf-8 -*-
"""Customer Intelligence: Segmentation using K-Means & PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgv7sN4rAa7KrGstroDZh9uf72WdX9nS
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import os
os.listdir()

!kaggle datasets download -d vishakhdapat/customer-segmentation-clustering

import zipfile

with zipfile.ZipFile('customer-segmentation-clustering.zip', 'r') as zip_ref:
    zip_ref.extractall()

import os
os.listdir()

# Load the data
df = pd.read_csv("customer_segmentation.csv")

df.head()
df.info()
df.columns

# 3. DATA CLEANING
df = df.dropna().copy()

# Fix date format (DD-MM-YYYY)
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True, errors='coerce')
df = df.dropna(subset=['Dt_Customer'])

# 4. FEATURE ENGINEERING (FINAL)

from datetime import datetime

# Age
df['Age'] = datetime.now().year - df['Year_Birth']

# Total Spending
spend_cols = [
    'MntWines','MntFruits','MntMeatProducts',
    'MntFishProducts','MntSweetProducts','MntGoldProds'
]
df['Total_Spending'] = df[spend_cols].sum(axis=1)

# Total Purchases
purchase_cols = [
    'NumDealsPurchases','NumWebPurchases',
    'NumCatalogPurchases','NumStorePurchases'
]
df['Total_Purchases'] = df[purchase_cols].sum(axis=1)

# Children
df['Children'] = df['Kidhome'] + df['Teenhome']

# Customer tenure (more robust)
today = pd.Timestamp.today()
df['Customer_Days'] = (today - df['Dt_Customer']).dt.days
# DATA VALIDATION
# Remove unrealistic ages
df = df[(df['Age'] > 18) & (df['Age'] < 100)]
# Remove negative tenure
df = df[df['Customer_Days'] >= 0]

# Optional: remove zero income (if needed)
df = df[df['Income'] > 0]

# 5. FEATURE SELECTION
features = [
    'Age','Income','Children','Customer_Days',
    'Total_Spending','Total_Purchases','Recency'
]

X = df[features]

# 6. SCALING

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 7. ELBOW METHOD

inertia = []

for k in range(1, 10):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

plt.plot(range(1,10), inertia, marker='o')
plt.title('Elbow Method')
plt.xlabel('Clusters')
plt.ylabel('Inertia')
plt.show()

# 8. FINAL KMEANS (k=4)

kmeans = KMeans(n_clusters=4, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# 9. SILHOUETTE SCORE
# ==============================
score = silhouette_score(X_scaled, df['Cluster'])
print("Silhouette Score:", score)

# 10. PCA VISUALIZATION

plt.scatter(X_pca[:,0], X_pca[:,1], c=df['Cluster'], cmap='viridis')

# 11. CLUSTER PROFILING

cluster_summary = df.groupby('Cluster')[features].mean()
print(cluster_summary)

# 12. HEATMAP
plt.figure(figsize=(10,6))
sns.heatmap(cluster_summary, annot=True, cmap='coolwarm')
plt.title('Cluster Profile Heatmap')
plt.show()

# Rebuild pipeline with new features
features = ['Income', 'Total_Spending', 'Total_Purchases', 'Recency']
X = df[features]

# Scaling
X_scaled = scaler.fit_transform(X)

# PCA
X_pca = pca.fit_transform(X_scaled)

# Clustering
kmeans = KMeans(n_clusters=4, random_state=42)
df['Cluster_New'] = kmeans.fit_predict(X_scaled)

df.to_csv("segmented_customers.csv", index=False)